# Generated by Django 3.2.5 on 2022-04-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='rss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rss.rss'),
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rss',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rss',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
